package lorenzo:discord-message-listener@0.1.0;

interface incoming-handler {
  use asterai:discord/types@0.1.0.{message};

  on-message: func(message: message);
}

world component {
  import asterai:host/api@1.0.0;
  import asterai:host-ws/connection@0.1.0;

  export asterai:host-ws/incoming-handler@0.1.0;
  export wasi:cli/run@0.2.0;
}
