package asterai:cli@0.1.0;

interface command {
  run: func(args: string, stdin: option<string>) -> result<string, string>;
}

interface common {
  ls: func(args: string, stdin: option<string>) -> result<string, string>;
  cat: func(args: string, stdin: option<string>) -> result<string, string>;
  cp: func(args: string, stdin: option<string>) -> result<string, string>;
  mv: func(args: string, stdin: option<string>) -> result<string, string>;
  rm: func(args: string, stdin: option<string>) -> result<string, string>;
  mkdir: func(args: string, stdin: option<string>) -> result<string, string>;
  touch: func(args: string, stdin: option<string>) -> result<string, string>;
  grep: func(args: string, stdin: option<string>) -> result<string, string>;
  sed: func(args: string, stdin: option<string>) -> result<string, string>;
  jq: func(args: string, stdin: option<string>) -> result<string, string>;
  find: func(args: string, stdin: option<string>) -> result<string, string>;
  head: func(args: string, stdin: option<string>) -> result<string, string>;
  tail: func(args: string, stdin: option<string>) -> result<string, string>;
  tree: func(args: string, stdin: option<string>) -> result<string, string>;
  tee: func(args: string, stdin: option<string>) -> result<string, string>;
  diff: func(args: string, stdin: option<string>) -> result<string, string>;
  wc: func(args: string, stdin: option<string>) -> result<string, string>;
  sort: func(args: string, stdin: option<string>) -> result<string, string>;
  uniq: func(args: string, stdin: option<string>) -> result<string, string>;
  cut: func(args: string, stdin: option<string>) -> result<string, string>;
  tr: func(args: string, stdin: option<string>) -> result<string, string>;
  stat: func(args: string, stdin: option<string>) -> result<string, string>;
  awk: func(args: string, stdin: option<string>) -> result<string, string>;
}

world component {
  import asterai:host/api@1.0.0;
  import asterai:fs/fs@1.0.0;

  export common;
}
