// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod asterai {
    pub mod host {
        #[allow(dead_code, clippy::all)]
        pub mod api {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct RuntimeInfo {
                pub version: _rt::String,
            }
            impl ::core::fmt::Debug for RuntimeInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("RuntimeInfo")
                        .field("version", &self.version)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ParamInfo {
                pub name: _rt::String,
                pub type_name: _rt::String,
                pub type_schema: _rt::String,
            }
            impl ::core::fmt::Debug for ParamInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ParamInfo")
                        .field("name", &self.name)
                        .field("type-name", &self.type_name)
                        .field("type-schema", &self.type_schema)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct TypeInfo {
                pub type_name: _rt::String,
                pub type_schema: _rt::String,
            }
            impl ::core::fmt::Debug for TypeInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("TypeInfo")
                        .field("type-name", &self.type_name)
                        .field("type-schema", &self.type_schema)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct FunctionInfo {
                pub name: _rt::String,
                pub interface_name: Option<_rt::String>,
                pub description: Option<_rt::String>,
                pub inputs: _rt::Vec<ParamInfo>,
                pub output: Option<TypeInfo>,
            }
            impl ::core::fmt::Debug for FunctionInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("FunctionInfo")
                        .field("name", &self.name)
                        .field("interface-name", &self.interface_name)
                        .field("description", &self.description)
                        .field("inputs", &self.inputs)
                        .field("output", &self.output)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ComponentInfo {
                pub name: _rt::String,
                pub version: _rt::String,
                pub interfaces: _rt::Vec<_rt::String>,
                pub description: Option<_rt::String>,
                pub functions: _rt::Vec<FunctionInfo>,
            }
            impl ::core::fmt::Debug for ComponentInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ComponentInfo")
                        .field("name", &self.name)
                        .field("version", &self.version)
                        .field("interfaces", &self.interfaces)
                        .field("description", &self.description)
                        .field("functions", &self.functions)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum CallErrorKind {
                ComponentNotFound,
                FunctionNotFound,
                InvalidArgs,
                InvocationFailed,
                SerializationFailed,
            }
            impl ::core::fmt::Debug for CallErrorKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        CallErrorKind::ComponentNotFound => {
                            f.debug_tuple("CallErrorKind::ComponentNotFound").finish()
                        }
                        CallErrorKind::FunctionNotFound => {
                            f.debug_tuple("CallErrorKind::FunctionNotFound").finish()
                        }
                        CallErrorKind::InvalidArgs => {
                            f.debug_tuple("CallErrorKind::InvalidArgs").finish()
                        }
                        CallErrorKind::InvocationFailed => {
                            f.debug_tuple("CallErrorKind::InvocationFailed").finish()
                        }
                        CallErrorKind::SerializationFailed => {
                            f.debug_tuple("CallErrorKind::SerializationFailed").finish()
                        }
                    }
                }
            }
            impl CallErrorKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> CallErrorKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => CallErrorKind::ComponentNotFound,
                        1 => CallErrorKind::FunctionNotFound,
                        2 => CallErrorKind::InvalidArgs,
                        3 => CallErrorKind::InvocationFailed,
                        4 => CallErrorKind::SerializationFailed,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct CallError {
                pub kind: CallErrorKind,
                pub message: _rt::String,
            }
            impl ::core::fmt::Debug for CallError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CallError")
                        .field("kind", &self.kind)
                        .field("message", &self.message)
                        .finish()
                }
            }
            impl ::core::fmt::Display for CallError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for CallError {}
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_runtime_info() -> RuntimeInfo {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "get-runtime-info"]
                        fn wit_import(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = *ptr0.add(0).cast::<*mut u8>();
                    let l2 = *ptr0.add(4).cast::<usize>();
                    let len3 = l2;
                    let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                    RuntimeInfo {
                        version: _rt::string_lift(bytes3),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn list_components() -> _rt::Vec<ComponentInfo> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "list-components"]
                        fn wit_import(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = *ptr0.add(0).cast::<*mut u8>();
                    let l2 = *ptr0.add(4).cast::<usize>();
                    let base52 = l1;
                    let len52 = l2;
                    let mut result52 = _rt::Vec::with_capacity(len52);
                    for i in 0..len52 {
                        let base = base52.add(i * 44);
                        let e52 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base.add(4).cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base.add(8).cast::<*mut u8>();
                            let l7 = *base.add(12).cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            let l9 = *base.add(16).cast::<*mut u8>();
                            let l10 = *base.add(20).cast::<usize>();
                            let base14 = l9;
                            let len14 = l10;
                            let mut result14 = _rt::Vec::with_capacity(len14);
                            for i in 0..len14 {
                                let base = base14.add(i * 8);
                                let e14 = {
                                    let l11 = *base.add(0).cast::<*mut u8>();
                                    let l12 = *base.add(4).cast::<usize>();
                                    let len13 = l12;
                                    let bytes13 = _rt::Vec::from_raw_parts(
                                        l11.cast(),
                                        len13,
                                        len13,
                                    );
                                    _rt::string_lift(bytes13)
                                };
                                result14.push(e14);
                            }
                            _rt::cabi_dealloc(base14, len14 * 8, 4);
                            let l15 = i32::from(*base.add(24).cast::<u8>());
                            let l19 = *base.add(36).cast::<*mut u8>();
                            let l20 = *base.add(40).cast::<usize>();
                            let base51 = l19;
                            let len51 = l20;
                            let mut result51 = _rt::Vec::with_capacity(len51);
                            for i in 0..len51 {
                                let base = base51.add(i * 60);
                                let e51 = {
                                    let l21 = *base.add(0).cast::<*mut u8>();
                                    let l22 = *base.add(4).cast::<usize>();
                                    let len23 = l22;
                                    let bytes23 = _rt::Vec::from_raw_parts(
                                        l21.cast(),
                                        len23,
                                        len23,
                                    );
                                    let l24 = i32::from(*base.add(8).cast::<u8>());
                                    let l28 = i32::from(*base.add(20).cast::<u8>());
                                    let l32 = *base.add(32).cast::<*mut u8>();
                                    let l33 = *base.add(36).cast::<usize>();
                                    let base43 = l32;
                                    let len43 = l33;
                                    let mut result43 = _rt::Vec::with_capacity(len43);
                                    for i in 0..len43 {
                                        let base = base43.add(i * 24);
                                        let e43 = {
                                            let l34 = *base.add(0).cast::<*mut u8>();
                                            let l35 = *base.add(4).cast::<usize>();
                                            let len36 = l35;
                                            let bytes36 = _rt::Vec::from_raw_parts(
                                                l34.cast(),
                                                len36,
                                                len36,
                                            );
                                            let l37 = *base.add(8).cast::<*mut u8>();
                                            let l38 = *base.add(12).cast::<usize>();
                                            let len39 = l38;
                                            let bytes39 = _rt::Vec::from_raw_parts(
                                                l37.cast(),
                                                len39,
                                                len39,
                                            );
                                            let l40 = *base.add(16).cast::<*mut u8>();
                                            let l41 = *base.add(20).cast::<usize>();
                                            let len42 = l41;
                                            let bytes42 = _rt::Vec::from_raw_parts(
                                                l40.cast(),
                                                len42,
                                                len42,
                                            );
                                            ParamInfo {
                                                name: _rt::string_lift(bytes36),
                                                type_name: _rt::string_lift(bytes39),
                                                type_schema: _rt::string_lift(bytes42),
                                            }
                                        };
                                        result43.push(e43);
                                    }
                                    _rt::cabi_dealloc(base43, len43 * 24, 4);
                                    let l44 = i32::from(*base.add(40).cast::<u8>());
                                    FunctionInfo {
                                        name: _rt::string_lift(bytes23),
                                        interface_name: match l24 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l25 = *base.add(12).cast::<*mut u8>();
                                                    let l26 = *base.add(16).cast::<usize>();
                                                    let len27 = l26;
                                                    let bytes27 = _rt::Vec::from_raw_parts(
                                                        l25.cast(),
                                                        len27,
                                                        len27,
                                                    );
                                                    _rt::string_lift(bytes27)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        description: match l28 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l29 = *base.add(24).cast::<*mut u8>();
                                                    let l30 = *base.add(28).cast::<usize>();
                                                    let len31 = l30;
                                                    let bytes31 = _rt::Vec::from_raw_parts(
                                                        l29.cast(),
                                                        len31,
                                                        len31,
                                                    );
                                                    _rt::string_lift(bytes31)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        inputs: result43,
                                        output: match l44 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l45 = *base.add(44).cast::<*mut u8>();
                                                    let l46 = *base.add(48).cast::<usize>();
                                                    let len47 = l46;
                                                    let bytes47 = _rt::Vec::from_raw_parts(
                                                        l45.cast(),
                                                        len47,
                                                        len47,
                                                    );
                                                    let l48 = *base.add(52).cast::<*mut u8>();
                                                    let l49 = *base.add(56).cast::<usize>();
                                                    let len50 = l49;
                                                    let bytes50 = _rt::Vec::from_raw_parts(
                                                        l48.cast(),
                                                        len50,
                                                        len50,
                                                    );
                                                    TypeInfo {
                                                        type_name: _rt::string_lift(bytes47),
                                                        type_schema: _rt::string_lift(bytes50),
                                                    }
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                    }
                                };
                                result51.push(e51);
                            }
                            _rt::cabi_dealloc(base51, len51 * 60, 4);
                            ComponentInfo {
                                name: _rt::string_lift(bytes5),
                                version: _rt::string_lift(bytes8),
                                interfaces: result14,
                                description: match l15 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l16 = *base.add(28).cast::<*mut u8>();
                                            let l17 = *base.add(32).cast::<usize>();
                                            let len18 = l17;
                                            let bytes18 = _rt::Vec::from_raw_parts(
                                                l16.cast(),
                                                len18,
                                                len18,
                                            );
                                            _rt::string_lift(bytes18)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                functions: result51,
                            }
                        };
                        result52.push(e52);
                    }
                    _rt::cabi_dealloc(base52, len52 * 44, 4);
                    result52
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn list_other_components() -> _rt::Vec<ComponentInfo> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "list-other-components"]
                        fn wit_import(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = *ptr0.add(0).cast::<*mut u8>();
                    let l2 = *ptr0.add(4).cast::<usize>();
                    let base52 = l1;
                    let len52 = l2;
                    let mut result52 = _rt::Vec::with_capacity(len52);
                    for i in 0..len52 {
                        let base = base52.add(i * 44);
                        let e52 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base.add(4).cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base.add(8).cast::<*mut u8>();
                            let l7 = *base.add(12).cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            let l9 = *base.add(16).cast::<*mut u8>();
                            let l10 = *base.add(20).cast::<usize>();
                            let base14 = l9;
                            let len14 = l10;
                            let mut result14 = _rt::Vec::with_capacity(len14);
                            for i in 0..len14 {
                                let base = base14.add(i * 8);
                                let e14 = {
                                    let l11 = *base.add(0).cast::<*mut u8>();
                                    let l12 = *base.add(4).cast::<usize>();
                                    let len13 = l12;
                                    let bytes13 = _rt::Vec::from_raw_parts(
                                        l11.cast(),
                                        len13,
                                        len13,
                                    );
                                    _rt::string_lift(bytes13)
                                };
                                result14.push(e14);
                            }
                            _rt::cabi_dealloc(base14, len14 * 8, 4);
                            let l15 = i32::from(*base.add(24).cast::<u8>());
                            let l19 = *base.add(36).cast::<*mut u8>();
                            let l20 = *base.add(40).cast::<usize>();
                            let base51 = l19;
                            let len51 = l20;
                            let mut result51 = _rt::Vec::with_capacity(len51);
                            for i in 0..len51 {
                                let base = base51.add(i * 60);
                                let e51 = {
                                    let l21 = *base.add(0).cast::<*mut u8>();
                                    let l22 = *base.add(4).cast::<usize>();
                                    let len23 = l22;
                                    let bytes23 = _rt::Vec::from_raw_parts(
                                        l21.cast(),
                                        len23,
                                        len23,
                                    );
                                    let l24 = i32::from(*base.add(8).cast::<u8>());
                                    let l28 = i32::from(*base.add(20).cast::<u8>());
                                    let l32 = *base.add(32).cast::<*mut u8>();
                                    let l33 = *base.add(36).cast::<usize>();
                                    let base43 = l32;
                                    let len43 = l33;
                                    let mut result43 = _rt::Vec::with_capacity(len43);
                                    for i in 0..len43 {
                                        let base = base43.add(i * 24);
                                        let e43 = {
                                            let l34 = *base.add(0).cast::<*mut u8>();
                                            let l35 = *base.add(4).cast::<usize>();
                                            let len36 = l35;
                                            let bytes36 = _rt::Vec::from_raw_parts(
                                                l34.cast(),
                                                len36,
                                                len36,
                                            );
                                            let l37 = *base.add(8).cast::<*mut u8>();
                                            let l38 = *base.add(12).cast::<usize>();
                                            let len39 = l38;
                                            let bytes39 = _rt::Vec::from_raw_parts(
                                                l37.cast(),
                                                len39,
                                                len39,
                                            );
                                            let l40 = *base.add(16).cast::<*mut u8>();
                                            let l41 = *base.add(20).cast::<usize>();
                                            let len42 = l41;
                                            let bytes42 = _rt::Vec::from_raw_parts(
                                                l40.cast(),
                                                len42,
                                                len42,
                                            );
                                            ParamInfo {
                                                name: _rt::string_lift(bytes36),
                                                type_name: _rt::string_lift(bytes39),
                                                type_schema: _rt::string_lift(bytes42),
                                            }
                                        };
                                        result43.push(e43);
                                    }
                                    _rt::cabi_dealloc(base43, len43 * 24, 4);
                                    let l44 = i32::from(*base.add(40).cast::<u8>());
                                    FunctionInfo {
                                        name: _rt::string_lift(bytes23),
                                        interface_name: match l24 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l25 = *base.add(12).cast::<*mut u8>();
                                                    let l26 = *base.add(16).cast::<usize>();
                                                    let len27 = l26;
                                                    let bytes27 = _rt::Vec::from_raw_parts(
                                                        l25.cast(),
                                                        len27,
                                                        len27,
                                                    );
                                                    _rt::string_lift(bytes27)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        description: match l28 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l29 = *base.add(24).cast::<*mut u8>();
                                                    let l30 = *base.add(28).cast::<usize>();
                                                    let len31 = l30;
                                                    let bytes31 = _rt::Vec::from_raw_parts(
                                                        l29.cast(),
                                                        len31,
                                                        len31,
                                                    );
                                                    _rt::string_lift(bytes31)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        inputs: result43,
                                        output: match l44 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l45 = *base.add(44).cast::<*mut u8>();
                                                    let l46 = *base.add(48).cast::<usize>();
                                                    let len47 = l46;
                                                    let bytes47 = _rt::Vec::from_raw_parts(
                                                        l45.cast(),
                                                        len47,
                                                        len47,
                                                    );
                                                    let l48 = *base.add(52).cast::<*mut u8>();
                                                    let l49 = *base.add(56).cast::<usize>();
                                                    let len50 = l49;
                                                    let bytes50 = _rt::Vec::from_raw_parts(
                                                        l48.cast(),
                                                        len50,
                                                        len50,
                                                    );
                                                    TypeInfo {
                                                        type_name: _rt::string_lift(bytes47),
                                                        type_schema: _rt::string_lift(bytes50),
                                                    }
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                    }
                                };
                                result51.push(e51);
                            }
                            _rt::cabi_dealloc(base51, len51 * 60, 4);
                            ComponentInfo {
                                name: _rt::string_lift(bytes5),
                                version: _rt::string_lift(bytes8),
                                interfaces: result14,
                                description: match l15 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l16 = *base.add(28).cast::<*mut u8>();
                                            let l17 = *base.add(32).cast::<usize>();
                                            let len18 = l17;
                                            let bytes18 = _rt::Vec::from_raw_parts(
                                                l16.cast(),
                                                len18,
                                                len18,
                                            );
                                            _rt::string_lift(bytes18)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                functions: result51,
                            }
                        };
                        result52.push(e52);
                    }
                    _rt::cabi_dealloc(base52, len52 * 44, 4);
                    result52
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_component(name: &str) -> Option<ComponentInfo> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 48]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 48]);
                    let vec0 = name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "get-component"]
                        fn wit_import(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0.cast_mut(), len0, ptr1);
                    let l2 = i32::from(*ptr1.add(0).cast::<u8>());
                    match l2 {
                        0 => None,
                        1 => {
                            let e = {
                                let l3 = *ptr1.add(4).cast::<*mut u8>();
                                let l4 = *ptr1.add(8).cast::<usize>();
                                let len5 = l4;
                                let bytes5 = _rt::Vec::from_raw_parts(
                                    l3.cast(),
                                    len5,
                                    len5,
                                );
                                let l6 = *ptr1.add(12).cast::<*mut u8>();
                                let l7 = *ptr1.add(16).cast::<usize>();
                                let len8 = l7;
                                let bytes8 = _rt::Vec::from_raw_parts(
                                    l6.cast(),
                                    len8,
                                    len8,
                                );
                                let l9 = *ptr1.add(20).cast::<*mut u8>();
                                let l10 = *ptr1.add(24).cast::<usize>();
                                let base14 = l9;
                                let len14 = l10;
                                let mut result14 = _rt::Vec::with_capacity(len14);
                                for i in 0..len14 {
                                    let base = base14.add(i * 8);
                                    let e14 = {
                                        let l11 = *base.add(0).cast::<*mut u8>();
                                        let l12 = *base.add(4).cast::<usize>();
                                        let len13 = l12;
                                        let bytes13 = _rt::Vec::from_raw_parts(
                                            l11.cast(),
                                            len13,
                                            len13,
                                        );
                                        _rt::string_lift(bytes13)
                                    };
                                    result14.push(e14);
                                }
                                _rt::cabi_dealloc(base14, len14 * 8, 4);
                                let l15 = i32::from(*ptr1.add(28).cast::<u8>());
                                let l19 = *ptr1.add(40).cast::<*mut u8>();
                                let l20 = *ptr1.add(44).cast::<usize>();
                                let base51 = l19;
                                let len51 = l20;
                                let mut result51 = _rt::Vec::with_capacity(len51);
                                for i in 0..len51 {
                                    let base = base51.add(i * 60);
                                    let e51 = {
                                        let l21 = *base.add(0).cast::<*mut u8>();
                                        let l22 = *base.add(4).cast::<usize>();
                                        let len23 = l22;
                                        let bytes23 = _rt::Vec::from_raw_parts(
                                            l21.cast(),
                                            len23,
                                            len23,
                                        );
                                        let l24 = i32::from(*base.add(8).cast::<u8>());
                                        let l28 = i32::from(*base.add(20).cast::<u8>());
                                        let l32 = *base.add(32).cast::<*mut u8>();
                                        let l33 = *base.add(36).cast::<usize>();
                                        let base43 = l32;
                                        let len43 = l33;
                                        let mut result43 = _rt::Vec::with_capacity(len43);
                                        for i in 0..len43 {
                                            let base = base43.add(i * 24);
                                            let e43 = {
                                                let l34 = *base.add(0).cast::<*mut u8>();
                                                let l35 = *base.add(4).cast::<usize>();
                                                let len36 = l35;
                                                let bytes36 = _rt::Vec::from_raw_parts(
                                                    l34.cast(),
                                                    len36,
                                                    len36,
                                                );
                                                let l37 = *base.add(8).cast::<*mut u8>();
                                                let l38 = *base.add(12).cast::<usize>();
                                                let len39 = l38;
                                                let bytes39 = _rt::Vec::from_raw_parts(
                                                    l37.cast(),
                                                    len39,
                                                    len39,
                                                );
                                                let l40 = *base.add(16).cast::<*mut u8>();
                                                let l41 = *base.add(20).cast::<usize>();
                                                let len42 = l41;
                                                let bytes42 = _rt::Vec::from_raw_parts(
                                                    l40.cast(),
                                                    len42,
                                                    len42,
                                                );
                                                ParamInfo {
                                                    name: _rt::string_lift(bytes36),
                                                    type_name: _rt::string_lift(bytes39),
                                                    type_schema: _rt::string_lift(bytes42),
                                                }
                                            };
                                            result43.push(e43);
                                        }
                                        _rt::cabi_dealloc(base43, len43 * 24, 4);
                                        let l44 = i32::from(*base.add(40).cast::<u8>());
                                        FunctionInfo {
                                            name: _rt::string_lift(bytes23),
                                            interface_name: match l24 {
                                                0 => None,
                                                1 => {
                                                    let e = {
                                                        let l25 = *base.add(12).cast::<*mut u8>();
                                                        let l26 = *base.add(16).cast::<usize>();
                                                        let len27 = l26;
                                                        let bytes27 = _rt::Vec::from_raw_parts(
                                                            l25.cast(),
                                                            len27,
                                                            len27,
                                                        );
                                                        _rt::string_lift(bytes27)
                                                    };
                                                    Some(e)
                                                }
                                                _ => _rt::invalid_enum_discriminant(),
                                            },
                                            description: match l28 {
                                                0 => None,
                                                1 => {
                                                    let e = {
                                                        let l29 = *base.add(24).cast::<*mut u8>();
                                                        let l30 = *base.add(28).cast::<usize>();
                                                        let len31 = l30;
                                                        let bytes31 = _rt::Vec::from_raw_parts(
                                                            l29.cast(),
                                                            len31,
                                                            len31,
                                                        );
                                                        _rt::string_lift(bytes31)
                                                    };
                                                    Some(e)
                                                }
                                                _ => _rt::invalid_enum_discriminant(),
                                            },
                                            inputs: result43,
                                            output: match l44 {
                                                0 => None,
                                                1 => {
                                                    let e = {
                                                        let l45 = *base.add(44).cast::<*mut u8>();
                                                        let l46 = *base.add(48).cast::<usize>();
                                                        let len47 = l46;
                                                        let bytes47 = _rt::Vec::from_raw_parts(
                                                            l45.cast(),
                                                            len47,
                                                            len47,
                                                        );
                                                        let l48 = *base.add(52).cast::<*mut u8>();
                                                        let l49 = *base.add(56).cast::<usize>();
                                                        let len50 = l49;
                                                        let bytes50 = _rt::Vec::from_raw_parts(
                                                            l48.cast(),
                                                            len50,
                                                            len50,
                                                        );
                                                        TypeInfo {
                                                            type_name: _rt::string_lift(bytes47),
                                                            type_schema: _rt::string_lift(bytes50),
                                                        }
                                                    };
                                                    Some(e)
                                                }
                                                _ => _rt::invalid_enum_discriminant(),
                                            },
                                        }
                                    };
                                    result51.push(e51);
                                }
                                _rt::cabi_dealloc(base51, len51 * 60, 4);
                                ComponentInfo {
                                    name: _rt::string_lift(bytes5),
                                    version: _rt::string_lift(bytes8),
                                    interfaces: result14,
                                    description: match l15 {
                                        0 => None,
                                        1 => {
                                            let e = {
                                                let l16 = *ptr1.add(32).cast::<*mut u8>();
                                                let l17 = *ptr1.add(36).cast::<usize>();
                                                let len18 = l17;
                                                let bytes18 = _rt::Vec::from_raw_parts(
                                                    l16.cast(),
                                                    len18,
                                                    len18,
                                                );
                                                _rt::string_lift(bytes18)
                                            };
                                            Some(e)
                                        }
                                        _ => _rt::invalid_enum_discriminant(),
                                    },
                                    functions: result51,
                                }
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn component_implements(
                component_name: &str,
                interface_name: &str,
            ) -> bool {
                unsafe {
                    let vec0 = component_name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = interface_name;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "component-implements"]
                        fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize) -> i32 {
                        unreachable!()
                    }
                    let ret = wit_import(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1);
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn call_component_function(
                component_name: &str,
                function_name: &str,
                args_json: &str,
            ) -> Result<_rt::String, CallError> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
                    let vec0 = component_name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = function_name;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = args_json;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "call-component-function"]
                        fn wit_import(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    wit_import(
                        ptr0.cast_mut(),
                        len0,
                        ptr1.cast_mut(),
                        len1,
                        ptr2.cast_mut(),
                        len2,
                        ptr3,
                    );
                    let l4 = i32::from(*ptr3.add(0).cast::<u8>());
                    match l4 {
                        0 => {
                            let e = {
                                let l5 = *ptr3.add(4).cast::<*mut u8>();
                                let l6 = *ptr3.add(8).cast::<usize>();
                                let len7 = l6;
                                let bytes7 = _rt::Vec::from_raw_parts(
                                    l5.cast(),
                                    len7,
                                    len7,
                                );
                                _rt::string_lift(bytes7)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l8 = i32::from(*ptr3.add(4).cast::<u8>());
                                let l9 = *ptr3.add(8).cast::<*mut u8>();
                                let l10 = *ptr3.add(12).cast::<usize>();
                                let len11 = l10;
                                let bytes11 = _rt::Vec::from_raw_parts(
                                    l9.cast(),
                                    len11,
                                    len11,
                                );
                                CallError {
                                    kind: CallErrorKind::_lift(l8 as u8),
                                    message: _rt::string_lift(bytes11),
                                }
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    }
                }
            }
        }
    }
    pub mod host_ws {
        #[allow(dead_code, clippy::all)]
        pub mod connection {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            pub type ConnectionId = u64;
            #[derive(Clone)]
            pub struct Config {
                pub url: _rt::String,
                pub headers: _rt::Vec<(_rt::String, _rt::String)>,
                pub auto_reconnect: bool,
            }
            impl ::core::fmt::Debug for Config {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("Config")
                        .field("url", &self.url)
                        .field("headers", &self.headers)
                        .field("auto-reconnect", &self.auto_reconnect)
                        .finish()
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn connect(config: &Config) -> Result<ConnectionId, _rt::String> {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
                    let Config {
                        url: url0,
                        headers: headers0,
                        auto_reconnect: auto_reconnect0,
                    } = config;
                    let vec1 = url0;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec5 = headers0;
                    let len5 = vec5.len();
                    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec5.len() * 16,
                        4,
                    );
                    let result5 = if layout5.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout5);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec5.into_iter().enumerate() {
                        let base = result5.add(i * 16);
                        {
                            let (t2_0, t2_1) = e;
                            let vec3 = t2_0;
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            *base.add(4).cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = t2_1;
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            *base.add(12).cast::<usize>() = len4;
                            *base.add(8).cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    }
                    let ptr6 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host-ws/connection@0.1.0")]
                    extern "C" {
                        #[link_name = "connect"]
                        fn wit_import(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: i32,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: i32,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    wit_import(
                        ptr1.cast_mut(),
                        len1,
                        result5,
                        len5,
                        match auto_reconnect0 {
                            true => 1,
                            false => 0,
                        },
                        ptr6,
                    );
                    let l7 = i32::from(*ptr6.add(0).cast::<u8>());
                    if layout5.size() != 0 {
                        _rt::alloc::dealloc(result5.cast(), layout5);
                    }
                    match l7 {
                        0 => {
                            let e = {
                                let l8 = *ptr6.add(8).cast::<i64>();
                                l8 as u64
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l9 = *ptr6.add(8).cast::<*mut u8>();
                                let l10 = *ptr6.add(12).cast::<usize>();
                                let len11 = l10;
                                let bytes11 = _rt::Vec::from_raw_parts(
                                    l9.cast(),
                                    len11,
                                    len11,
                                );
                                _rt::string_lift(bytes11)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn send(id: ConnectionId, data: &[u8]) -> Result<(), _rt::String> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 12]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
                    let vec0 = data;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host-ws/connection@0.1.0")]
                    extern "C" {
                        #[link_name = "send"]
                        fn wit_import(_: i64, _: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: i64, _: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    wit_import(_rt::as_i64(id), ptr0.cast_mut(), len0, ptr1);
                    let l2 = i32::from(*ptr1.add(0).cast::<u8>());
                    match l2 {
                        0 => {
                            let e = ();
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l3 = *ptr1.add(4).cast::<*mut u8>();
                                let l4 = *ptr1.add(8).cast::<usize>();
                                let len5 = l4;
                                let bytes5 = _rt::Vec::from_raw_parts(
                                    l3.cast(),
                                    len5,
                                    len5,
                                );
                                _rt::string_lift(bytes5)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn close(id: ConnectionId) {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host-ws/connection@0.1.0")]
                    extern "C" {
                        #[link_name = "close"]
                        fn wit_import(_: i64);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: i64) {
                        unreachable!()
                    }
                    wit_import(_rt::as_i64(id));
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod asterai {
        pub mod host_ws {
            #[allow(dead_code, clippy::all)]
            pub mod incoming_handler {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ConnectionId = super::super::super::super::asterai::host_ws::connection::ConnectionId;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_message_cabi<T: Guest>(
                    arg0: i64,
                    arg1: *mut u8,
                    arg2: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    T::on_message(
                        arg0 as u64,
                        _rt::Vec::from_raw_parts(arg1.cast(), len0, len0),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_close_cabi<T: Guest>(
                    arg0: i64,
                    arg1: i32,
                    arg2: *mut u8,
                    arg3: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg3;
                    let bytes0 = _rt::Vec::from_raw_parts(arg2.cast(), len0, len0);
                    T::on_close(arg0 as u64, arg1 as u16, _rt::string_lift(bytes0));
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_error_cabi<T: Guest>(
                    arg0: i64,
                    arg1: *mut u8,
                    arg2: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    T::on_error(arg0 as u64, _rt::string_lift(bytes0));
                }
                pub trait Guest {
                    fn on_message(id: ConnectionId, data: _rt::Vec<u8>);
                    fn on_close(id: ConnectionId, code: u16, reason: _rt::String);
                    fn on_error(id: ConnectionId, message: _rt::String);
                }
                #[doc(hidden)]
                macro_rules! __export_asterai_host_ws_incoming_handler_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[export_name =
                        "asterai:host-ws/incoming-handler@0.1.0#on-message"] unsafe
                        extern "C" fn export_on_message(arg0 : i64, arg1 : * mut u8, arg2
                        : usize,) { $($path_to_types)*:: _export_on_message_cabi::<$ty >
                        (arg0, arg1, arg2) } #[export_name =
                        "asterai:host-ws/incoming-handler@0.1.0#on-close"] unsafe extern
                        "C" fn export_on_close(arg0 : i64, arg1 : i32, arg2 : * mut u8,
                        arg3 : usize,) { $($path_to_types)*:: _export_on_close_cabi::<$ty
                        > (arg0, arg1, arg2, arg3) } #[export_name =
                        "asterai:host-ws/incoming-handler@0.1.0#on-error"] unsafe extern
                        "C" fn export_on_error(arg0 : i64, arg1 : * mut u8, arg2 :
                        usize,) { $($path_to_types)*:: _export_on_error_cabi::<$ty >
                        (arg0, arg1, arg2) } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_asterai_host_ws_incoming_handler_0_1_0_cabi;
            }
        }
    }
    pub mod wasi {
        pub mod cli {
            #[allow(dead_code, clippy::all)]
            pub mod run {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_run_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::run();
                    let result1 = match result0 {
                        Ok(_) => 0i32,
                        Err(_) => 1i32,
                    };
                    result1
                }
                pub trait Guest {
                    fn run() -> Result<(), ()>;
                }
                #[doc(hidden)]
                macro_rules! __export_wasi_cli_run_0_2_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[export_name = "wasi:cli/run@0.2.0#run"] unsafe
                        extern "C" fn export_run() -> i32 { $($path_to_types)*::
                        _export_run_cabi::<$ty > () } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_wasi_cli_run_0_2_0_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            core::hint::unreachable_unchecked()
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub use alloc_crate::alloc;
    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }
    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }
    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }
    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::asterai::host_ws::incoming_handler::__export_asterai_host_ws_incoming_handler_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::asterai::host_ws::incoming_handler); $($path_to_types_root)*::
        exports::wasi::cli::run::__export_wasi_cli_run_0_2_0_cabi!($ty with_types_in
        $($path_to_types_root)*:: exports::wasi::cli::run);
    };
}
#[doc(inline)]
pub(crate) use __export_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:asterai:discord-message-listener@0.1.0:component:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1331] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb3\x09\x01A\x02\x01\
A\x09\x01B!\x01r\x01\x07versions\x04\0\x0cruntime-info\x03\0\0\x01r\x03\x04names\
\x09type-names\x0btype-schemas\x04\0\x0aparam-info\x03\0\x02\x01r\x02\x09type-na\
mes\x0btype-schemas\x04\0\x09type-info\x03\0\x04\x01ks\x01p\x03\x01k\x05\x01r\x05\
\x04names\x0einterface-name\x06\x0bdescription\x06\x06inputs\x07\x06output\x08\x04\
\0\x0dfunction-info\x03\0\x09\x01ps\x01p\x0a\x01r\x05\x04names\x07versions\x0ain\
terfaces\x0b\x0bdescription\x06\x09functions\x0c\x04\0\x0ecomponent-info\x03\0\x0d\
\x01m\x05\x13component-not-found\x12function-not-found\x0cinvalid-args\x11invoca\
tion-failed\x14serialization-failed\x04\0\x0fcall-error-kind\x03\0\x0f\x01r\x02\x04\
kind\x10\x07messages\x04\0\x0acall-error\x03\0\x11\x01@\0\0\x01\x04\0\x10get-run\
time-info\x01\x13\x01p\x0e\x01@\0\0\x14\x04\0\x0flist-components\x01\x15\x04\0\x15\
list-other-components\x01\x15\x01k\x0e\x01@\x01\x04names\0\x16\x04\0\x0dget-comp\
onent\x01\x17\x01@\x02\x0ecomponent-names\x0einterface-names\0\x7f\x04\0\x14comp\
onent-implements\x01\x18\x01j\x01s\x01\x12\x01@\x03\x0ecomponent-names\x0dfuncti\
on-names\x09args-jsons\0\x19\x04\0\x17call-component-function\x01\x1a\x03\0\x16a\
sterai:host/api@1.0.0\x05\0\x01B\x0f\x01w\x04\0\x0dconnection-id\x03\0\0\x01o\x02\
ss\x01p\x02\x01r\x03\x03urls\x07headers\x03\x0eauto-reconnect\x7f\x04\0\x06confi\
g\x03\0\x04\x01j\x01\x01\x01s\x01@\x01\x06config\x05\0\x06\x04\0\x07connect\x01\x07\
\x01p}\x01j\0\x01s\x01@\x02\x02id\x01\x04data\x08\0\x09\x04\0\x04send\x01\x0a\x01\
@\x01\x02id\x01\x01\0\x04\0\x05close\x01\x0b\x03\0\x20asterai:host-ws/connection\
@0.1.0\x05\x01\x02\x03\0\x01\x0dconnection-id\x01B\x09\x02\x03\x02\x01\x02\x04\0\
\x0dconnection-id\x03\0\0\x01p}\x01@\x02\x02id\x01\x04data\x02\x01\0\x04\0\x0aon\
-message\x01\x03\x01@\x03\x02id\x01\x04code{\x06reasons\x01\0\x04\0\x08on-close\x01\
\x04\x01@\x02\x02id\x01\x07messages\x01\0\x04\0\x08on-error\x01\x05\x04\0&astera\
i:host-ws/incoming-handler@0.1.0\x05\x03\x01B\x03\x01j\0\0\x01@\0\0\0\x04\0\x03r\
un\x01\x01\x04\0\x12wasi:cli/run@0.2.0\x05\x04\x04\00asterai:discord-message-lis\
tener/component@0.1.0\x04\0\x0b\x0f\x01\0\x09component\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.220.0\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
