package asterai:excel@0.1.0;

interface types {
  record sheet-info {
    index: u32,
    name: string,
    rows: u32,
    cols: u32,
    csv: string,
  }
}

interface api {
  use types.{sheet-info};

  parse-binary: func(data: list<u8>) -> result<list<sheet-info>, string>;
  parse-base64: func(data: string) -> result<list<sheet-info>, string>;
}

world component {
  export api;
  export types;
}
