// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod asterai {
    pub mod host {
        #[allow(dead_code, clippy::all)]
        pub mod api {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct RuntimeInfo {
                pub version: _rt::String,
            }
            impl ::core::fmt::Debug for RuntimeInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("RuntimeInfo")
                        .field("version", &self.version)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ComponentInfo {
                pub name: _rt::String,
                pub version: _rt::String,
                pub interfaces: _rt::Vec<_rt::String>,
            }
            impl ::core::fmt::Debug for ComponentInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ComponentInfo")
                        .field("name", &self.name)
                        .field("version", &self.version)
                        .field("interfaces", &self.interfaces)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum CallErrorKind {
                ComponentNotFound,
                FunctionNotFound,
                InvalidArgs,
                InvocationFailed,
                SerializationFailed,
            }
            impl ::core::fmt::Debug for CallErrorKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        CallErrorKind::ComponentNotFound => {
                            f.debug_tuple("CallErrorKind::ComponentNotFound").finish()
                        }
                        CallErrorKind::FunctionNotFound => {
                            f.debug_tuple("CallErrorKind::FunctionNotFound").finish()
                        }
                        CallErrorKind::InvalidArgs => {
                            f.debug_tuple("CallErrorKind::InvalidArgs").finish()
                        }
                        CallErrorKind::InvocationFailed => {
                            f.debug_tuple("CallErrorKind::InvocationFailed").finish()
                        }
                        CallErrorKind::SerializationFailed => {
                            f.debug_tuple("CallErrorKind::SerializationFailed").finish()
                        }
                    }
                }
            }
            impl CallErrorKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> CallErrorKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => CallErrorKind::ComponentNotFound,
                        1 => CallErrorKind::FunctionNotFound,
                        2 => CallErrorKind::InvalidArgs,
                        3 => CallErrorKind::InvocationFailed,
                        4 => CallErrorKind::SerializationFailed,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct CallError {
                pub kind: CallErrorKind,
                pub message: _rt::String,
            }
            impl ::core::fmt::Debug for CallError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CallError")
                        .field("kind", &self.kind)
                        .field("message", &self.message)
                        .finish()
                }
            }
            impl ::core::fmt::Display for CallError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for CallError {}
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_runtime_info() -> RuntimeInfo {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "get-runtime-info"]
                        fn wit_import(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = *ptr0.add(0).cast::<*mut u8>();
                    let l2 = *ptr0.add(4).cast::<usize>();
                    let len3 = l2;
                    let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                    RuntimeInfo {
                        version: _rt::string_lift(bytes3),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn list_components() -> _rt::Vec<ComponentInfo> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "list-components"]
                        fn wit_import(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = *ptr0.add(0).cast::<*mut u8>();
                    let l2 = *ptr0.add(4).cast::<usize>();
                    let base15 = l1;
                    let len15 = l2;
                    let mut result15 = _rt::Vec::with_capacity(len15);
                    for i in 0..len15 {
                        let base = base15.add(i * 24);
                        let e15 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base.add(4).cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base.add(8).cast::<*mut u8>();
                            let l7 = *base.add(12).cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            let l9 = *base.add(16).cast::<*mut u8>();
                            let l10 = *base.add(20).cast::<usize>();
                            let base14 = l9;
                            let len14 = l10;
                            let mut result14 = _rt::Vec::with_capacity(len14);
                            for i in 0..len14 {
                                let base = base14.add(i * 8);
                                let e14 = {
                                    let l11 = *base.add(0).cast::<*mut u8>();
                                    let l12 = *base.add(4).cast::<usize>();
                                    let len13 = l12;
                                    let bytes13 = _rt::Vec::from_raw_parts(
                                        l11.cast(),
                                        len13,
                                        len13,
                                    );
                                    _rt::string_lift(bytes13)
                                };
                                result14.push(e14);
                            }
                            _rt::cabi_dealloc(base14, len14 * 8, 4);
                            ComponentInfo {
                                name: _rt::string_lift(bytes5),
                                version: _rt::string_lift(bytes8),
                                interfaces: result14,
                            }
                        };
                        result15.push(e15);
                    }
                    _rt::cabi_dealloc(base15, len15 * 24, 4);
                    result15
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn list_other_components() -> _rt::Vec<ComponentInfo> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "list-other-components"]
                        fn wit_import(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = *ptr0.add(0).cast::<*mut u8>();
                    let l2 = *ptr0.add(4).cast::<usize>();
                    let base15 = l1;
                    let len15 = l2;
                    let mut result15 = _rt::Vec::with_capacity(len15);
                    for i in 0..len15 {
                        let base = base15.add(i * 24);
                        let e15 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base.add(4).cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base.add(8).cast::<*mut u8>();
                            let l7 = *base.add(12).cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            let l9 = *base.add(16).cast::<*mut u8>();
                            let l10 = *base.add(20).cast::<usize>();
                            let base14 = l9;
                            let len14 = l10;
                            let mut result14 = _rt::Vec::with_capacity(len14);
                            for i in 0..len14 {
                                let base = base14.add(i * 8);
                                let e14 = {
                                    let l11 = *base.add(0).cast::<*mut u8>();
                                    let l12 = *base.add(4).cast::<usize>();
                                    let len13 = l12;
                                    let bytes13 = _rt::Vec::from_raw_parts(
                                        l11.cast(),
                                        len13,
                                        len13,
                                    );
                                    _rt::string_lift(bytes13)
                                };
                                result14.push(e14);
                            }
                            _rt::cabi_dealloc(base14, len14 * 8, 4);
                            ComponentInfo {
                                name: _rt::string_lift(bytes5),
                                version: _rt::string_lift(bytes8),
                                interfaces: result14,
                            }
                        };
                        result15.push(e15);
                    }
                    _rt::cabi_dealloc(base15, len15 * 24, 4);
                    result15
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_component(name: &str) -> Option<ComponentInfo> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 28]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 28]);
                    let vec0 = name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "get-component"]
                        fn wit_import(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0.cast_mut(), len0, ptr1);
                    let l2 = i32::from(*ptr1.add(0).cast::<u8>());
                    match l2 {
                        0 => None,
                        1 => {
                            let e = {
                                let l3 = *ptr1.add(4).cast::<*mut u8>();
                                let l4 = *ptr1.add(8).cast::<usize>();
                                let len5 = l4;
                                let bytes5 = _rt::Vec::from_raw_parts(
                                    l3.cast(),
                                    len5,
                                    len5,
                                );
                                let l6 = *ptr1.add(12).cast::<*mut u8>();
                                let l7 = *ptr1.add(16).cast::<usize>();
                                let len8 = l7;
                                let bytes8 = _rt::Vec::from_raw_parts(
                                    l6.cast(),
                                    len8,
                                    len8,
                                );
                                let l9 = *ptr1.add(20).cast::<*mut u8>();
                                let l10 = *ptr1.add(24).cast::<usize>();
                                let base14 = l9;
                                let len14 = l10;
                                let mut result14 = _rt::Vec::with_capacity(len14);
                                for i in 0..len14 {
                                    let base = base14.add(i * 8);
                                    let e14 = {
                                        let l11 = *base.add(0).cast::<*mut u8>();
                                        let l12 = *base.add(4).cast::<usize>();
                                        let len13 = l12;
                                        let bytes13 = _rt::Vec::from_raw_parts(
                                            l11.cast(),
                                            len13,
                                            len13,
                                        );
                                        _rt::string_lift(bytes13)
                                    };
                                    result14.push(e14);
                                }
                                _rt::cabi_dealloc(base14, len14 * 8, 4);
                                ComponentInfo {
                                    name: _rt::string_lift(bytes5),
                                    version: _rt::string_lift(bytes8),
                                    interfaces: result14,
                                }
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn component_implements(
                component_name: &str,
                interface_name: &str,
            ) -> bool {
                unsafe {
                    let vec0 = component_name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = interface_name;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "component-implements"]
                        fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize) -> i32 {
                        unreachable!()
                    }
                    let ret = wit_import(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1);
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn call_component_function(
                component_name: &str,
                function_name: &str,
                args_json: &str,
            ) -> Result<_rt::String, CallError> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
                    let vec0 = component_name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = function_name;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = args_json;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "call-component-function"]
                        fn wit_import(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    wit_import(
                        ptr0.cast_mut(),
                        len0,
                        ptr1.cast_mut(),
                        len1,
                        ptr2.cast_mut(),
                        len2,
                        ptr3,
                    );
                    let l4 = i32::from(*ptr3.add(0).cast::<u8>());
                    match l4 {
                        0 => {
                            let e = {
                                let l5 = *ptr3.add(4).cast::<*mut u8>();
                                let l6 = *ptr3.add(8).cast::<usize>();
                                let len7 = l6;
                                let bytes7 = _rt::Vec::from_raw_parts(
                                    l5.cast(),
                                    len7,
                                    len7,
                                );
                                _rt::string_lift(bytes7)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l8 = i32::from(*ptr3.add(4).cast::<u8>());
                                let l9 = *ptr3.add(8).cast::<*mut u8>();
                                let l10 = *ptr3.add(12).cast::<usize>();
                                let len11 = l10;
                                let bytes11 = _rt::Vec::from_raw_parts(
                                    l9.cast(),
                                    len11,
                                    len11,
                                );
                                CallError {
                                    kind: CallErrorKind::_lift(l8 as u8),
                                    message: _rt::string_lift(bytes11),
                                }
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod asterai {
        pub mod llm {
            #[allow(dead_code, clippy::all)]
            pub mod llm {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_greet_cabi<T: Guest>(arg0: *mut u8, arg1: usize) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    T::greet(_rt::string_lift(bytes0));
                }
                pub trait Guest {
                    fn greet(name: _rt::String);
                }
                #[doc(hidden)]
                macro_rules! __export_asterai_llm_llm_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[export_name = "asterai:llm/llm@0.1.0#greet"]
                        unsafe extern "C" fn export_greet(arg0 : * mut u8, arg1 : usize,)
                        { $($path_to_types)*:: _export_greet_cabi::<$ty > (arg0, arg1) }
                        };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_asterai_llm_llm_0_1_0_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            core::hint::unreachable_unchecked()
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::asterai::llm::llm::__export_asterai_llm_llm_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::asterai::llm::llm);
    };
}
#[doc(inline)]
pub(crate) use __export_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:asterai:llm@0.1.0:component:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 733] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xdd\x04\x01A\x02\x01\
A\x04\x01B\x17\x01r\x01\x07versions\x04\0\x0cruntime-info\x03\0\0\x01ps\x01r\x03\
\x04names\x07versions\x0ainterfaces\x02\x04\0\x0ecomponent-info\x03\0\x03\x01m\x05\
\x13component-not-found\x12function-not-found\x0cinvalid-args\x11invocation-fail\
ed\x14serialization-failed\x04\0\x0fcall-error-kind\x03\0\x05\x01r\x02\x04kind\x06\
\x07messages\x04\0\x0acall-error\x03\0\x07\x01@\0\0\x01\x04\0\x10get-runtime-inf\
o\x01\x09\x01p\x04\x01@\0\0\x0a\x04\0\x0flist-components\x01\x0b\x04\0\x15list-o\
ther-components\x01\x0b\x01k\x04\x01@\x01\x04names\0\x0c\x04\0\x0dget-component\x01\
\x0d\x01@\x02\x0ecomponent-names\x0einterface-names\0\x7f\x04\0\x14component-imp\
lements\x01\x0e\x01j\x01s\x01\x08\x01@\x03\x0ecomponent-names\x0dfunction-names\x09\
args-jsons\0\x0f\x04\0\x17call-component-function\x01\x10\x03\0\x16asterai:host/\
api@1.0.0\x05\0\x01B\x02\x01@\x01\x04names\x01\0\x04\0\x05greet\x01\0\x04\0\x15a\
sterai:llm/llm@0.1.0\x05\x01\x04\0\x1basterai:llm/component@0.1.0\x04\0\x0b\x0f\x01\
\0\x09component\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\
\x070.220.0\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
